### ISSUE TITLE
t/dlog.t fails  

### ISSUE THREAD

**Issue by errietta** [frioux/Log-Contextual#11] opened 2017-05-20 22:30 UTC
perl 5.24.1 is literally just installed through perlbrew - there shouldn't be any extra modules other than defaults.

````
errietta@Moltres [2]  ~ % perl -v        

This is perl 5, version 24, subversion 1 (v5.24.1) built for x86_64-linux
(with 1 registered patch, see perl -V for more detail)

Copyright 1987-2017, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

errietta@Moltres [2]  ~ % eval $(perl -Mlocal::lib=--deactivate-all)                                                         0 3464 22:59:46 Sat 20.05.2017

errietta@Moltres [2]  ~ % perlbrew list                          
perl-5.10.1
* perl-5.24.1

errietta@Moltres [2]  ~ % perlbrew switch perl-5.24.1    
errietta@Moltres [2]  ~ % echo $PERL5LIB 
/home/errietta/perl5/lib/perl5/x86_64-linux-gnu-thread-multi

errietta@Moltres [2]  ~ % perl -e "print join ' ', @INC";   
/home/errietta/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/errietta/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.1/x86_64-linux /home/errietta/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.1 /home/errietta/perl5/perlbrew/perls/perl-5.24.1/lib/5.24.1/x86_64-linux /home/errietta/perl5/perlbrew/perls/perl-5.24.1/lib/5.24.1 

errietta@Moltres [2]  ~ % ls deps   
errietta@Moltres [2]  ~ %             
errietta@Moltres [2]  ~ % cpanm -Ldeps Log::Contextual > output     

--> Working on Log::Contextual
Fetching http://www.cpan.org/authors/id/F/FR/FREW/Log-Contextual-0.007000.tar.gz ... OK
Configuring Log-Contextual-0.007000 ... OK
==> Found dependencies: Test::Fatal, Moo, Data::Dumper::Concise, Exporter::Declare
--> Working on Test::Fatal
Fetching http://www.cpan.org/authors/id/R/RJ/RJBS/Test-Fatal-0.014.tar.gz ... OK
Configuring Test-Fatal-0.014 ... OK
==> Found dependencies: Try::Tiny
--> Working on Try::Tiny
Fetching http://www.cpan.org/authors/id/E/ET/ETHER/Try-Tiny-0.28.tar.gz ... OK
Configuring Try-Tiny-0.28 ... OK
Building and testing Try-Tiny-0.28 ... OK
Successfully installed Try-Tiny-0.28
Building and testing Test-Fatal-0.014 ... OK
Successfully installed Test-Fatal-0.014
--> Working on Moo
Fetching http://www.cpan.org/authors/id/H/HA/HAARG/Moo-2.003002.tar.gz ... OK
Configuring Moo-2.003002 ... OK
==> Found dependencies: Sub::Defer, Sub::Quote, Devel::GlobalDestruction, Class::Method::Modifiers, Module::Runtime, Role::Tiny
--> Working on Sub::Defer
Fetching http://www.cpan.org/authors/id/H/HA/HAARG/Sub-Quote-2.003001.tar.gz ... OK
Configuring Sub-Quote-2.003001 ... OK
Building and testing Sub-Quote-2.003001 ... OK
Successfully installed Sub-Quote-2.003001
--> Working on Devel::GlobalDestruction
Fetching http://www.cpan.org/authors/id/H/HA/HAARG/Devel-GlobalDestruction-0.14.tar.gz ... OK
Configuring Devel-GlobalDestruction-0.14 ... OK
==> Found dependencies: Sub::Exporter::Progressive
--> Working on Sub::Exporter::Progressive
Fetching http://www.cpan.org/authors/id/F/FR/FREW/Sub-Exporter-Progressive-0.001013.tar.gz ... OK
Configuring Sub-Exporter-Progressive-0.001013 ... OK
Building and testing Sub-Exporter-Progressive-0.001013 ... OK
Successfully installed Sub-Exporter-Progressive-0.001013
Building and testing Devel-GlobalDestruction-0.14 ... OK
Successfully installed Devel-GlobalDestruction-0.14
--> Working on Class::Method::Modifiers
Fetching http://www.cpan.org/authors/id/E/ET/ETHER/Class-Method-Modifiers-2.12.tar.gz ... OK
Configuring Class-Method-Modifiers-2.12 ... OK
==> Found dependencies: Test::Requires
--> Working on Test::Requires
Fetching http://www.cpan.org/authors/id/T/TO/TOKUHIROM/Test-Requires-0.10.tar.gz ... OK
Configuring Test-Requires-0.10 ... OK
Building and testing Test-Requires-0.10 ... OK
Successfully installed Test-Requires-0.10
Building and testing Class-Method-Modifiers-2.12 ... OK
Successfully installed Class-Method-Modifiers-2.12
--> Working on Module::Runtime
Fetching http://www.cpan.org/authors/id/Z/ZE/ZEFRAM/Module-Runtime-0.014.tar.gz ... OK
==> Found dependencies: Module::Build
--> Working on Module::Build
Fetching http://www.cpan.org/authors/id/L/LE/LEONT/Module-Build-0.4222.tar.gz ... OK
Configuring Module-Build-0.4222 ... OK
Building and testing Module-Build-0.4222 ... OK
Successfully installed Module-Build-0.4222
Configuring Module-Runtime-0.014 ... OK
Building and testing Module-Runtime-0.014 ... OK
Successfully installed Module-Runtime-0.014
--> Working on Role::Tiny
Fetching http://www.cpan.org/authors/id/H/HA/HAARG/Role-Tiny-2.000005.tar.gz ... OK
Configuring Role-Tiny-2.000005 ... OK
Building and testing Role-Tiny-2.000005 ... OK
Successfully installed Role-Tiny-2.000005
Building and testing Moo-2.003002 ... OK
Successfully installed Moo-2.003002
--> Working on Data::Dumper::Concise
Fetching http://www.cpan.org/authors/id/E/ET/ETHER/Data-Dumper-Concise-2.023.tar.gz ... OK
Configuring Data-Dumper-Concise-2.023 ... OK
Building and testing Data-Dumper-Concise-2.023 ... OK
Successfully installed Data-Dumper-Concise-2.023
--> Working on Exporter::Declare
Fetching http://www.cpan.org/authors/id/E/EX/EXODIST/Exporter-Declare-0.114.tar.gz ... OK
Configuring Exporter-Declare-0.114 ... OK
==> Found dependencies: Test::Exception, Meta::Builder, Fennec::Lite, aliased
--> Working on Test::Exception
Fetching http://www.cpan.org/authors/id/E/EX/EXODIST/Test-Exception-0.43.tar.gz ... OK
Configuring Test-Exception-0.43 ... OK
==> Found dependencies: Sub::Uplevel
--> Working on Sub::Uplevel
Fetching http://www.cpan.org/authors/id/D/DA/DAGOLDEN/Sub-Uplevel-0.2800.tar.gz ... OK
Configuring Sub-Uplevel-0.2800 ... OK
Building and testing Sub-Uplevel-0.2800 ... OK
Successfully installed Sub-Uplevel-0.2800
Building and testing Test-Exception-0.43 ... OK
Successfully installed Test-Exception-0.43
--> Working on Meta::Builder
Fetching http://www.cpan.org/authors/id/E/EX/EXODIST/Meta-Builder-0.003.tar.gz ... OK
Configuring Meta-Builder-0.003 ... OK
==> Found dependencies: Fennec::Lite
--> Working on Fennec::Lite
Fetching http://www.cpan.org/authors/id/E/EX/EXODIST/Fennec-Lite-0.004.tar.gz ... OK
Configuring Fennec-Lite-0.004 ... OK
Building and testing Fennec-Lite-0.004 ... OK
Successfully installed Fennec-Lite-0.004
Building and testing Meta-Builder-0.003 ... OK
Successfully installed Meta-Builder-0.003
--> Working on aliased
Fetching http://www.cpan.org/authors/id/E/ET/ETHER/aliased-0.34.tar.gz ... OK
==> Found dependencies: Module::Build::Tiny
--> Working on Module::Build::Tiny
Fetching http://www.cpan.org/authors/id/L/LE/LEONT/Module-Build-Tiny-0.039.tar.gz ... OK
==> Found dependencies: ExtUtils::Helpers, ExtUtils::Config, ExtUtils::InstallPaths
--> Working on ExtUtils::Helpers
Fetching http://www.cpan.org/authors/id/L/LE/LEONT/ExtUtils-Helpers-0.026.tar.gz ... OK
Configuring ExtUtils-Helpers-0.026 ... OK
Building and testing ExtUtils-Helpers-0.026 ... OK
Successfully installed ExtUtils-Helpers-0.026
--> Working on ExtUtils::Config
Fetching http://www.cpan.org/authors/id/L/LE/LEONT/ExtUtils-Config-0.008.tar.gz ... OK
Configuring ExtUtils-Config-0.008 ... OK
Building and testing ExtUtils-Config-0.008 ... OK
Successfully installed ExtUtils-Config-0.008
--> Working on ExtUtils::InstallPaths
Fetching http://www.cpan.org/authors/id/L/LE/LEONT/ExtUtils-InstallPaths-0.011.tar.gz ... OK
Configuring ExtUtils-InstallPaths-0.011 ... OK
Building and testing ExtUtils-InstallPaths-0.011 ... OK
Successfully installed ExtUtils-InstallPaths-0.011
Configuring Module-Build-Tiny-0.039 ... OK
Building and testing Module-Build-Tiny-0.039 ... OK
Successfully installed Module-Build-Tiny-0.039
Configuring aliased-0.34 ... OK
Building and testing aliased-0.34 ... OK
Successfully installed aliased-0.34
Building and testing Exporter-Declare-0.114 ... OK
Successfully installed Exporter-Declare-0.114
Building and testing Log-Contextual-0.007000 ... FAIL
22 distributions installed

cpanm (App::cpanminus) 1.7043 on perl 5.024001 built for x86_64-linux
Work directory is /home/errietta/.cpanm/work/1495319135.11291
You have make /usr/bin/make
You have /usr/bin/wget
You have /bin/tar: tar (GNU tar) 1.27.1
Copyright © 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
Searching Log::Contextual () on cpanmetadb ...
--> Working on Log::Contextual
Fetching http://www.cpan.org/authors/id/F/FR/FREW/Log-Contextual-0.007000.tar.gz
-> OK
Unpacking Log-Contextual-0.007000.tar.gz
Entering Log-Contextual-0.007000
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.10_02)
Configuring Log-Contextual-0.007000
Running Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Log::Contextual
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Carp 0 ... Yes (1.40)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.10_02)
Checking if you have Exporter::Declare 0.111 ... Yes (0.114)
Checking if you have Test::Fatal 0 ... Yes (0.014)
Checking if you have Moo 1.003 ... Yes (2.003002)
Checking if you have Data::Dumper::Concise 0 ... Yes (2.023)
Checking if you have Scalar::Util 0 ... Yes (1.42_02)
Building and testing Log-Contextual-0.007000
cp lib/Log/Contextual/Role/Router/HasLogger.pm blib/lib/Log/Contextual/Role/Router/HasLogger.pm
cp lib/Log/Contextual/Router.pm blib/lib/Log/Contextual/Router.pm
cp lib/Log/Contextual/Role/Router.pm blib/lib/Log/Contextual/Role/Router.pm
cp lib/Log/Contextual/WarnLogger.pm blib/lib/Log/Contextual/WarnLogger.pm
cp lib/Log/Contextual/Role/Router/WithLogger.pm blib/lib/Log/Contextual/Role/Router/WithLogger.pm
cp lib/Log/Contextual/TeeLogger.pm blib/lib/Log/Contextual/TeeLogger.pm
cp lib/Log/Contextual/Easy/Package.pm blib/lib/Log/Contextual/Easy/Package.pm
cp lib/Log/Contextual.pm blib/lib/Log/Contextual.pm
cp lib/Log/Contextual/Role/Router/SetLogger.pm blib/lib/Log/Contextual/Role/Router/SetLogger.pm
cp lib/Log/Contextual/Easy/Default.pm blib/lib/Log/Contextual/Easy/Default.pm
cp lib/Log/Contextual/SimpleLogger.pm blib/lib/Log/Contextual/SimpleLogger.pm
PERL_DL_NONLAZY=1 "/home/errietta/perl5/perlbrew/perls/perl-5.24.1/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/arg.t ..................... ok
t/base.t .................... ok
t/caller.t .................. ok
t/default_import.t .......... ok
t/default_logger.t .......... ok

#   Failed test 'Output for DlogS_debug is correct'
#   at t/dlog.t line 41.
#          got: '[debug] Look ma, data: [
#   "frew",
#   "bar",
#   "baz",
# ]
# '
#     expected: '[debug] Look ma, data: [
#   "frew",
#   "bar",
#   "baz"
# ]
# '

#   Failed test 'Output for DlogS_trace is correct'
#   at t/dlog.t line 41.
#          got: '[trace] Look ma, data: [
#   "frew",
#   "bar",
#   "baz",
# ]
# '
#     expected: '[trace] Look ma, data: [
#   "frew",
#   "bar",
#   "baz"
# ]
# '

#   Failed test 'Output for DlogS_warn is correct'
#   at t/dlog.t line 41.
#          got: '[warn] Look ma, data: [
#   "frew",
#   "bar",
#   "baz",
# ]
# '
#     expected: '[warn] Look ma, data: [
#   "frew",
#   "bar",
#   "baz"
# ]
# '

#   Failed test 'Output for DlogS_info is correct'
#   at t/dlog.t line 41.
#          got: '[info] Look ma, data: [
#   "frew",
#   "bar",
#   "baz",
# ]
# '
#     expected: '[info] Look ma, data: [
#   "frew",
#   "bar",
#   "baz"
# ]
# '

#   Failed test 'Output for DlogS_error is correct'
#   at t/dlog.t line 41.
#          got: '[error] Look ma, data: [
#   "frew",
#   "bar",
#   "baz",
# ]
# '
#     expected: '[error] Look ma, data: [
#   "frew",
#   "bar",
#   "baz"
# ]
# '

#   Failed test 'Output for DlogS_fatal is correct'
#   at t/dlog.t line 41.
#          got: '[fatal] Look ma, data: [
#   "frew",
#   "bar",
#   "baz",
# ]
# '
#     expected: '[fatal] Look ma, data: [
#   "frew",
#   "bar",
#   "baz"
# ]
# '
# Looks like you failed 6 tests of 36.
t/dlog.t .................... 
Dubious, test returned 6 (wstat 1536, 0x600)
Failed 6/36 subtests 
t/easy.t .................... ok
t/eg.t ...................... ok
t/has_logger.t .............. ok

#   Failed test 'Output for DlogS_custom is correct'
#   at t/log-with-levels.t line 42.
#          got: 'Look ma, data: [
#   "frew",
#   "bar",
#   "baz",
# ]
# '
#     expected: 'Look ma, data: [
#   "frew",
#   "bar",
#   "baz"
# ]
# '
# Looks like you failed 1 test of 24.
t/log-with-levels.t ......... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/24 subtests 
t/log.t ..................... ok
t/log4perl.t ................ skipped: Log::Log4perl 1.29 not installed
t/package_logger.t .......... ok
t/perltidy.t ................ skipped: Set TIDY_TESTING if you want to run this test
t/release-pod-syntax.t ...... skipped: these tests are for release candidate testing
t/router_api.t .............. ok
t/rt83267-begin.t ........... ok
t/rt83267.t ................. ok
t/simplelogger.t ............ ok
t/warnlogger-with-levels.t .. ok
t/warnlogger.t .............. ok
t/yell-loudly.t ............. ok

Test Summary Report
-------------------
t/dlog.t                  (Wstat: 1536 Tests: 36 Failed: 6)
  Failed tests:  4, 10, 16, 22, 28, 34
  Non-zero exit status: 6
t/log-with-levels.t       (Wstat: 256 Tests: 24 Failed: 1)
  Failed test:  9
  Non-zero exit status: 1
Files=22, Tests=292,  2 wallclock secs ( 0.05 usr  0.02 sys +  0.98 cusr  0.10 csys =  1.15 CPU)
Result: FAIL
Failed 2/22 test programs. 7/292 subtests failed.
make: *** [test_dynamic] Error 255
-> FAIL Installing Log::Contextual failed. See /home/errietta/.cpanm/work/1495319135.11291/build.log for details. Retry with --force to force install it.
 ````

**Comment by simcop2387** [comment] 2017-05-20 22:43
This looks to be caused by Data::Dumper::Concise 2.023 that added the Trailingcomma option by default

**Comment by errietta** [comment] 2017-05-20 22:52
Agreed, looks like D::D::C.

**Comment by frioux** [comment] 2017-05-20 22:53
Well no need to close it! I'll still release a fix to resolve this.

--

**Comment by errietta** [comment] 2017-05-21 10:45
Thanks @frioux . Another weirdness was that it's fine with Data::Dumper 2.124 but not in 2.161 !

**Comment by frioux** [comment] 2017-05-21 14:51
Ok I released a version which should fix  this.  Please re-open if you find other DD related oddities.  Thanks for reporting!

**Closed by frioux** 2017-05-21 14:51 UTC
